[package]
name = "mocktail"
version = "0.1.0"
authors = ["Mark Smith <judy@judy.co.uk>"]
edition = "2018"

[dependencies]
mongodb = "1.1.1"

tokio = "0.2.22"
futures = "0.3"
serde = "1.0.116"
chrono = "0.4.19"
serde_json = "1.0.59"
actix-web = "3.2.0"
# thiserror = "1.0.21"